const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Setting = sequelize.define('Setting', {
  themeColor: { type: DataTypes.STRING, defaultValue: 'white' },
  primaryColor: { type: DataTypes.STRING, defaultValue: '' },
  accentColor: { type: DataTypes.STRING, defaultValue: '' },
  surfaceColor: { type: DataTypes.STRING, defaultValue: '' },
  textColor: { type: DataTypes.STRING, defaultValue: '' },
  mutedColor: { type: DataTypes.STRING, defaultValue: '' },
  headingColor: { type: DataTypes.STRING, defaultValue: '' },
  backgroundBaseColor: { type: DataTypes.STRING, defaultValue: '' },
  backgroundImage: { type: DataTypes.STRING, defaultValue: '' },
  backgroundOpacity: { type: DataTypes.FLOAT, defaultValue: 1.0 },
  socialInstagram: { type: DataTypes.STRING, defaultValue: '' },
  socialFacebook: { type: DataTypes.STRING, defaultValue: '' },
  socialThreads: { type: DataTypes.STRING, defaultValue: '' },
  brandKicker: { type: DataTypes.STRING, defaultValue: 'Carreira e cursos' },
  brandName: { type: DataTypes.STRING, defaultValue: 'Agência de Emprego' },
  footerDescription: { type: DataTypes.TEXT, defaultValue: 'Agência de Emprego conecta vagas, cursos e orientação profissional em uma experiência mais clara e confiável.' },
  customCss: { type: DataTypes.TEXT, defaultValue: '' },
  cardImageHeight: { type: DataTypes.INTEGER, defaultValue: 200 },
  navbarPosition: { type: DataTypes.STRING, defaultValue: 'top' },
  navbarAlignment: { type: DataTypes.STRING, defaultValue: 'end' },
  navbarFontSize: { type: DataTypes.INTEGER, defaultValue: 15 },
  navbarItemGap: { type: DataTypes.INTEGER, defaultValue: 10 },
  navbarItemPaddingX: { type: DataTypes.INTEGER, defaultValue: 16 },
  navbarItemMinHeight: { type: DataTypes.INTEGER, defaultValue: 44 },
  navbarWrap: { type: DataTypes.STRING, defaultValue: 'nowrap' },
  heroKicker: { type: DataTypes.STRING, defaultValue: 'Plataforma profissional para carreira' },
  heroTitle: { type: DataTypes.STRING, defaultValue: 'Conecte talento, contratação e qualificação em uma vitrine que transmite confiança.' },
  heroDescription: { type: DataTypes.TEXT, defaultValue: 'Sua agência agora apresenta vagas e cursos em uma experiência mais forte comercialmente: clara para quem busca oportunidade e convincente para quem quer divulgar serviços e atrair candidatos qualificados.' },
  heroHeight: { type: DataTypes.INTEGER, defaultValue: 0 },
  heroPadding: { type: DataTypes.INTEGER, defaultValue: 42 },
  heroTitleSize: { type: DataTypes.INTEGER, defaultValue: 72 },
  heroContentWidth: { type: DataTypes.INTEGER, defaultValue: 720 },
  heroKickerSize: { type: DataTypes.INTEGER, defaultValue: 12 },
  heroDescriptionSize: { type: DataTypes.INTEGER, defaultValue: 17 },
  heroTextAlign: { type: DataTypes.STRING, defaultValue: 'left' },
  heroPlacement: { type: DataTypes.STRING, defaultValue: 'after_top_ads' },
  heroContentOffsetX: { type: DataTypes.INTEGER, defaultValue: 0 },
  heroContentOffsetY: { type: DataTypes.INTEGER, defaultValue: 0 },
  heroEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
  heroShowKicker: { type: DataTypes.BOOLEAN, defaultValue: true },
  heroShowDescription: { type: DataTypes.BOOLEAN, defaultValue: true },
  heroShowActions: { type: DataTypes.BOOLEAN, defaultValue: true },
  heroShowStats: { type: DataTypes.BOOLEAN, defaultValue: true },
  heroMaxWidth: { type: DataTypes.INTEGER, defaultValue: 0 },
  heroBorderRadius: { type: DataTypes.INTEGER, defaultValue: 28 },
  heroBackgroundColor: { type: DataTypes.STRING, defaultValue: '' },
  heroContentBackgroundColor: { type: DataTypes.STRING, defaultValue: '' },
  heroTextColor: { type: DataTypes.STRING, defaultValue: '' },
  heroMutedTextColor: { type: DataTypes.STRING, defaultValue: '' },
  heroActionPrimaryLabel: { type: DataTypes.STRING, defaultValue: 'Cadastrar currículo' },
  heroActionPrimaryLink: { type: DataTypes.STRING, defaultValue: '/acesso-candidato?section=register-candidate' },
  heroActionSecondaryLabel: { type: DataTypes.STRING, defaultValue: 'Explorar vagas' },
  heroActionSecondaryLink: { type: DataTypes.STRING, defaultValue: '/vagas' },
  heroActionTertiaryLabel: { type: DataTypes.STRING, defaultValue: 'Conhecer cursos' },
  heroActionTertiaryLink: { type: DataTypes.STRING, defaultValue: '/cursos' },
  heroActionQuaternaryLabel: { type: DataTypes.STRING, defaultValue: 'Falar com a equipe' },
  heroActionQuaternaryLink: { type: DataTypes.STRING, defaultValue: '/contato' },
  heroStat1Value: { type: DataTypes.STRING, defaultValue: '' },
  heroStat1Label: { type: DataTypes.STRING, defaultValue: 'vagas com apresentação mais objetiva' },
  heroStat2Value: { type: DataTypes.STRING, defaultValue: '' },
  heroStat2Label: { type: DataTypes.STRING, defaultValue: 'cursos posicionados para conversão' },
  heroStat3Value: { type: DataTypes.STRING, defaultValue: '' },
  heroStat3Label: { type: DataTypes.STRING, defaultValue: 'editais públicos com cronograma e quadro de vagas' },
  topAdsOffsetX: { type: DataTypes.INTEGER, defaultValue: 0 },
  topAdsOffsetY: { type: DataTypes.INTEGER, defaultValue: 0 },
  topAdsMaxWidth: { type: DataTypes.INTEGER, defaultValue: 1200 },
  topAdsAlignment: { type: DataTypes.STRING, defaultValue: 'center' },
  muralAdsOffsetX: { type: DataTypes.INTEGER, defaultValue: 0 },
  muralAdsOffsetY: { type: DataTypes.INTEGER, defaultValue: 0 },
  muralAdsMaxWidth: { type: DataTypes.INTEGER, defaultValue: 1200 },
  muralAdsAlignment: { type: DataTypes.STRING, defaultValue: 'center' },
  previewDialogMaxWidth: { type: DataTypes.INTEGER, defaultValue: 1380 },
  previewDialogMinHeight: { type: DataTypes.INTEGER, defaultValue: 82 },
  previewInfoPanelWidth: { type: DataTypes.INTEGER, defaultValue: 380 },
  previewSizePreset: { type: DataTypes.STRING, defaultValue: 'large' },
  detailPdfMinHeight: { type: DataTypes.INTEGER, defaultValue: 1200 },
  adminAccessMode: { type: DataTypes.STRING, defaultValue: 'lock' },
  floatingAdminButtonLabel: { type: DataTypes.STRING, defaultValue: 'Acesso admin' },
  adminSidebarConfig: { type: DataTypes.TEXT, defaultValue: '' },
  companyShowcaseEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
  companyShowcaseTitle: { type: DataTypes.STRING, defaultValue: 'Empresas que divulgam vagas na plataforma' },
  companyShowcaseDescription: { type: DataTypes.TEXT, defaultValue: 'Painel institucional com empresas que autorizaram a divulgacao publica de dados corporativos para fortalecer a confianca de quem busca vagas.' },
  companyShowcasePlacement: { type: DataTypes.STRING, defaultValue: 'after_mural' },
  companyShowcaseDirection: { type: DataTypes.STRING, defaultValue: 'left' },
  companyShowcaseSpeed: { type: DataTypes.INTEGER, defaultValue: 38 },
  companyShowcaseCardMinWidth: { type: DataTypes.INTEGER, defaultValue: 240 },
  companyShowcaseShowWebsite: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyShowcaseShowLocation: { type: DataTypes.BOOLEAN, defaultValue: true },
  companyShowcaseShowSector: { type: DataTypes.BOOLEAN, defaultValue: true },
  homeSectionOrder: { type: DataTypes.TEXT, defaultValue: 'top_ads,hero,jobs,mural,company_showcase,contact,courses,public_selections' },
  commercialPaymentLink: { type: DataTypes.STRING, defaultValue: 'https://mpago.la/2BYr2CS' },
  commercialPaymentAmount: { type: DataTypes.STRING, defaultValue: 'R$ 50,00' },
  commercialPaymentPlan: { type: DataTypes.STRING, defaultValue: 'Mensal' },
  commercialFreeTrialMonths: { type: DataTypes.INTEGER, defaultValue: 1 },
  smtpHost: { type: DataTypes.STRING, defaultValue: '' },
  smtpPort: { type: DataTypes.STRING, defaultValue: '' },
  smtpUser: { type: DataTypes.STRING, defaultValue: '' },
  smtpPass: { type: DataTypes.STRING, defaultValue: '' },
  smtpFrom: { type: DataTypes.STRING, defaultValue: '' },
  smtpEncryption: { type: DataTypes.STRING, defaultValue: 'tls' },
  mercadoPagoAccessToken: { type: DataTypes.STRING, defaultValue: '' },
  homeSurveyEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
  homeSurveyTitle: { type: DataTypes.STRING, defaultValue: 'Sua opinião é fundamental!' },
  homeSurveySubtitle: { type: DataTypes.TEXT, defaultValue: 'Ajude-nos a melhorar nossa plataforma. Responda à nossa pesquisa de satisfação em poucos segundos.' },
  googleAdSenseCode: { type: DataTypes.TEXT, defaultValue: '' }
});

module.exports = Setting;
