const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const User = sequelize.define('User', {
  name: { type: DataTypes.STRING, allowNull: false },
  email: { type: DataTypes.STRING, allowNull: false, unique: true },
  password: { type: DataTypes.STRING },
  googleId: { type: DataTypes.STRING },
  avatar: { type: DataTypes.STRING },
  cpf: { type: DataTypes.STRING },
  phone: { type: DataTypes.STRING },
  whatsapp: { type: DataTypes.STRING },
  address: { type: DataTypes.STRING },
  city: { type: DataTypes.STRING },
  state: { type: DataTypes.STRING },
  objective: { type: DataTypes.TEXT },
  desiredRole: { type: DataTypes.STRING },
  salaryExpectation: { type: DataTypes.STRING },
  linkedinUrl: { type: DataTypes.STRING },
  resumePdf: { type: DataTypes.STRING },
  sex: { type: DataTypes.STRING },
  maritalStatus: { type: DataTypes.STRING },
  birthDate: { type: DataTypes.DATEONLY },
  currentlyEmployed: { type: DataTypes.STRING },
  disability: { type: DataTypes.STRING },
  hasDriverLicense: { type: DataTypes.BOOLEAN, defaultValue: false },
  driverLicenseCategory: { type: DataTypes.STRING },
  homePhone: { type: DataTypes.STRING },
  commercialPhone: { type: DataTypes.STRING },
  commercialPhoneExtension: { type: DataTypes.STRING },
  mobilePhone: { type: DataTypes.STRING },
  personalWebsite: { type: DataTypes.STRING },
  addressNumber: { type: DataTypes.STRING },
  addressComplement: { type: DataTypes.STRING },
  neighborhood: { type: DataTypes.STRING },
  zipCode: { type: DataTypes.STRING },
  country: { type: DataTypes.STRING, defaultValue: 'Brasil' },
  desiredWorkCities: { type: DataTypes.STRING },
  intendedArea: { type: DataTypes.STRING },
  hierarchyLevel: { type: DataTypes.STRING },
  englishLevel: { type: DataTypes.STRING },
  spanishLevel: { type: DataTypes.STRING },
  otherLanguage1Name: { type: DataTypes.STRING },
  otherLanguage1Level: { type: DataTypes.STRING },
  otherLanguage2Name: { type: DataTypes.STRING },
  otherLanguage2Level: { type: DataTypes.STRING },
  otherLanguage3Name: { type: DataTypes.STRING },
  otherLanguage3Level: { type: DataTypes.STRING },
  miniResume: { type: DataTypes.TEXT },
  courseHistory: { type: DataTypes.TEXT },
  experienceHistory: { type: DataTypes.TEXT },
  portalReferral: { type: DataTypes.STRING },
  companyProfileType: { type: DataTypes.STRING },
  companyDocumentType: { type: DataTypes.STRING },
  companyDocument: { type: DataTypes.STRING },
  companyLegalName: { type: DataTypes.STRING },
  companyTradeName: { type: DataTypes.STRING },
  companyStateRegistration: { type: DataTypes.STRING },
  companySector: { type: DataTypes.STRING },
  companyResponsibleName: { type: DataTypes.STRING },
  companyResponsibleCpf: { type: DataTypes.STRING },
  companyPhone: { type: DataTypes.STRING },
  companyCorporateEmail: { type: DataTypes.STRING },
  companyZipCode: { type: DataTypes.STRING },
  companyWebsite: { type: DataTypes.STRING },
  companyPrivacyAccepted: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyPrivacyAcceptedAt: { type: DataTypes.DATE },
  companyTermsAccepted: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyTermsAcceptedAt: { type: DataTypes.DATE },
  companyShowcaseEnabled: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyShowcaseLgpdConsent: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyPublicDisplayName: { type: DataTypes.STRING },
  companyPublicSummary: { type: DataTypes.TEXT },
  companyShowcaseOrder: { type: DataTypes.INTEGER, defaultValue: 0 },
  companyPaymentValidated: { type: DataTypes.BOOLEAN, defaultValue: false },
  companyPaymentValidatedAt: { type: DataTypes.DATE },
  companyApprovedAt: { type: DataTypes.DATE },
  companyApprovedBy: { type: DataTypes.INTEGER },
  companyApprovalNotes: { type: DataTypes.TEXT },
  passwordResetTokenHash: { type: DataTypes.STRING },
  passwordResetCodeHash: { type: DataTypes.STRING },
  passwordResetExpiresAt: { type: DataTypes.DATE },
  passwordResetAttemptCount: { type: DataTypes.INTEGER, defaultValue: 0 },
  passwordResetLastSentAt: { type: DataTypes.DATE },
  passwordResetVerifiedAt: { type: DataTypes.DATE },
  providerLogin: {
    type: DataTypes.STRING,
    defaultValue: 'email',
    validate: { isIn: [['email', 'google', 'linkedin']] }
  },
  status: {
    type: DataTypes.STRING,
    defaultValue: 'pendente',
    validate: { isIn: [['ativo', 'pendente', 'bloqueado']] }
  },
  role: {
    type: DataTypes.STRING,
    defaultValue: 'candidato',
    validate: { isIn: [['admin', 'empresa', 'candidato', 'user']] }
  }
});

module.exports = User;
